use_frameworks!


source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'AHFMDownloadListManager_Example' do
  pod 'AHFMDownloadListManager', :path => '../'

  target 'AHFMDownloadListManager_Tests' do
    inherit! :search_paths

    
  end
end
